### PR TITLE
Recipes for buffer added

### PR DESCRIPTION
**Pull request by bas-rustenburg**
My basic chemistry skills are a little rusty, so I used a buffer calculator on the internet... http://www.biomol.net/en/tools/buffercalculator.htm

### CODE REVIEW

**Comment by jchodera** [comment]
Cool!  We should see if we can get LabMinds to eventually release some of their buffer calculation tools as Python modules.

**Comment by jchodera** [comment]
Wouldn't we want these to all be at the same pH?

Also, any chance you can make a list of buffer components we need to buy?

**Comment by bas-rustenburg** [comment]
They're all at pH 7.8.

Working on the list already. ;)

**Comment by jchodera** [comment]
Thanks!

**Comment by bas-rustenburg** [comment]
@jchodera, I added list of things to order.

**Comment by jchodera** [comment]
Thanks!

**Pull request merged**
